### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by AluminiumTech** [AluminiumTech/AluminiumCoreLib#20]
I'm opening this issue to check to see if the License Change can go ahead.

@evilarceus  Is it ok for the licensing of code that you've contributed to be changed from MIT to MPL 2.0?

The code in question is the AluminiumCoreLib Java code related to detecting Hardware info and also a few other things.

Thanks.

**Comment by evilarceus** [comment]
Absolutely! :)

**Comment by AluminiumTech** [comment]
Awesome! Thank you :)
